@echo off
del Main.class
del Main.nxj
del Phase1.class
del Phase2.class
del Phase3.class
del Phase4.class
del Phase5.class
del Phase6.class
del Phase7.class
del Phase1.nxj
del Phase2.nxj
del Phase3.nxj
del Phase4.nxj
del Phase5.nxj
del Phase6.nxj
del Phase7.nxj
cd helper
del ActionHelper.class
del IceThread.class
cd ..\